start:
    pnpm run start

format:
    pnpm run format

lint:
    pnpm run lint

tc:
    pnpm run typecheck

check:
    just format && just lint && just tc

unit filter="":
    pnpm run unit-test {{filter}}

e2e filter="":
    pnpm run package && pnpm run e2e-test --grep="{{filter}}"

e2e-show filter="":
    pnpm run package && pnpm run e2e-show --grep="{{filter}}"

test:
    just unit && just e2e

coverage:
    pnpm run package && pnpm run coverage

codegen:
    pnpm run package && npx tsx scripts/playwright-codegen.ts

print-py-nodes file:
    npx tsx scripts/print-py-nodes.ts {{file}}

print-py-nodes-tree file:
    npx tsx scripts/print-py-nodes-tree.ts {{file}}

gif input:
    #!/usr/bin/env bash
    set -euo pipefail
    input="{{input}}"
    output="${input%.mov}.gif"
    echo "Converting $input to $output"
    ffmpeg -i "$input" -vf "fps=15,scale=320:-1:flags=lanczos" -y "$output"