start:
    pnpm run start

lint:
    pnpm run lint

unit:
    pnpm run unit-test

e2e:
    pnpm run package && pnpm run e2e-test

test:
    just unit && just e2e

codegen:
    npx tsx e2e/playwright-codegen.ts