packages:
  - .

ignoredBuiltDependencies:
  - msgpackr-extract

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "@vscode/ripgrep"
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - protobufjs
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-typescript

patchedDependencies:
  tree-sitter@0.25.0: patches/tree-sitter@0.25.0.patch
