ignoredBuiltDependencies:
  - msgpackr-extract

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - tree-sitter-python
