/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorkspaceIdRouteImport } from './routes/w.$workspaceId'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w.$workspaceId.index'
import { Route as WWorkspaceIdFFilePathRouteImport } from './routes/w.$workspaceId.f.$filePath'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdRoute = WWorkspaceIdRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)
const WWorkspaceIdFFilePathRoute = WWorkspaceIdFFilePathRouteImport.update({
  id: '/f/$filePath',
  path: '/f/$filePath',
  getParentRoute: () => WWorkspaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/f/$filePath': typeof WWorkspaceIdFFilePathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/f/$filePath': typeof WWorkspaceIdFFilePathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteWithChildren
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/f/$filePath': typeof WWorkspaceIdFFilePathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$workspaceId'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/f/$filePath'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/w/$workspaceId' | '/w/$workspaceId/f/$filePath'
  id:
    | '__root__'
    | '/'
    | '/w/$workspaceId'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/f/$filePath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WWorkspaceIdRoute: typeof WWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
    '/w/$workspaceId/f/$filePath': {
      id: '/w/$workspaceId/f/$filePath'
      path: '/f/$filePath'
      fullPath: '/w/$workspaceId/f/$filePath'
      preLoaderRoute: typeof WWorkspaceIdFFilePathRouteImport
      parentRoute: typeof WWorkspaceIdRoute
    }
  }
}

interface WWorkspaceIdRouteChildren {
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdFFilePathRoute: typeof WWorkspaceIdFFilePathRoute
}

const WWorkspaceIdRouteChildren: WWorkspaceIdRouteChildren = {
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdFFilePathRoute: WWorkspaceIdFFilePathRoute,
}

const WWorkspaceIdRouteWithChildren = WWorkspaceIdRoute._addFileChildren(
  WWorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WWorkspaceIdRoute: WWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
