start:
    pnpm run start

build:
    pnpm run build

preview:
    pnpm run preview

format:
    pnpm run format

format-check:
    pnpm run format-check

lint:
    pnpm run lint

tc:
    pnpm run typecheck

check:
    just format-check && just lint && just tc

