start:
    pnpm run start

build:
    pnpm run build

preview:
    pnpm run preview

format:
    pnpm run format

lint:
    pnpm run lint

tc:
    pnpm run typecheck

check:
    just format && just lint && just tc

