/**
 * @vitest-environment jsdom
 */

import * as React from "react"
import { act } from "react"
import { $convertFromMarkdownString } from "@lexical/markdown"
import { LexicalErrorBoundary } from "@lexical/react/LexicalErrorBoundary"
import { MarkdownShortcutPlugin } from "@lexical/react/LexicalMarkdownShortcutPlugin"
import { RichTextPlugin } from "@lexical/react/LexicalRichTextPlugin"
import { describe, expect, it, vi } from "vitest"

import { serializeEditorToMarkdown } from "@/lib/editor"
import { ContentEditable } from "@/components/editor/content-editable"
import { editorConfig } from "@/components/editor/editor"
import { initializeUnitTest } from "@/components/editor/test-utils"
import { MARKDOWN_TRANSFORMERS } from "@/components/editor/transformers/markdown"

vi.mock("web-tree-sitter", () => {
  return {
    Parser: class {
      static init = vi.fn()
      setLanguage = vi.fn()
      parse = vi.fn(() => ({
        rootNode: {
          children: [],
        },
      }))
    },
  }
})

vi.mock("@/lib/parser/languages", () => {
  const mockQuery = {
    exec: () => [],
  }

  const mockLanguage = {
    query: () => mockQuery,
  }

  return {
    default: Promise.resolve({
      Markdown: mockLanguage,
    }),
  }
})

const Plugins = React.memo(function Plugins() {
  return (
    <div className="relative">
      <div className="relative">
        <RichTextPlugin
          contentEditable={
            <div className="h-full flex flex-1 min-h-0">
              <div className="h-full flex-1 min-h-0">
                <ContentEditable
                  placeholder={""}
                  className="ContentEditable__root relative block h-full min-h-0 flex-1 overflow-auto px-8 py-4 focus:outline-none"
                />
              </div>
            </div>
          }
          ErrorBoundary={LexicalErrorBoundary}
        />

        <MarkdownShortcutPlugin transformers={MARKDOWN_TRANSFORMERS} />
      </div>
    </div>
  )
})

describe("Markdown isomorphism", () => {
  initializeUnitTest(
    (testEnv) => {
      it("markdown file with checklist should have isomorphic parsing & serialization", async () => {
        const text = `# [CHECKLIST TYPE] Checklist: [FEATURE NAME]

**Purpose**: [Brief description of what this checklist covers]
**Created**: [DATE]
**Feature**: [Link to spec.md or relevant documentation]

**Note**: This checklist is generated by the \`/speckit.checklist\` command based on feature context and requirements.

## [Category 1]

- [ ] CHK001 First checklist item with clear action
- [ ] CHK002 Second checklist item
- [ ] CHK003 Third checklist item

## [Category 2]

- [ ] CHK004 Another category item
- [ ] CHK005 Item with specific criteria
- [ ] CHK006 Final item in this category

## Notes

- Check items off as completed: \`[x]\`
- Add comments or findings inline
- Link to relevant resources or documentation
- Items are numbered sequentially for easy reference`

        await act(async () => {
          testEnv.editor.update(
            () =>
              $convertFromMarkdownString(
                text,
                MARKDOWN_TRANSFORMERS,
                undefined,
                true
              ),
            { discrete: true }
          )
        })
        const result = serializeEditorToMarkdown(
          testEnv.editor.getEditorState()
        )
        expect(result).toBe(text)
      })

      it("markdown file with table should have isomorphic parsing & serialization", async () => {
        const text = `|  | Feature | Supported | Notes |
| --- | --- | --- | --- |
|  | Tables | ✅ | Full support |
|  | Task Lists | ✅ | Interactive |
|  | Strikethrough | ✅ | ~~Like this~~ |`

        await act(async () => {
          testEnv.editor.update(
            () =>
              $convertFromMarkdownString(
                text,
                MARKDOWN_TRANSFORMERS,
                undefined,
                true
              ),
            { discrete: true }
          )
        })
        const result = serializeEditorToMarkdown(
          testEnv.editor.getEditorState()
        )
        expect(result).toBe(text)
      })

      it("markdown file with mermaid diagram should have isomorphic parsing & serialization", async () => {
        const text = `# Architecture Diagram

\`\`\`mermaid
graph TD;
    A[User Interface] -->|sends request| B[API Server]
    B -->|queries| C[Database]
    C -->|returns data| B
    B -->|returns response| A
\`\`\`

Here's a simple flow showing how data moves through the system.`

        await act(async () => {
          testEnv.editor.update(
            () =>
              $convertFromMarkdownString(
                text,
                MARKDOWN_TRANSFORMERS,
                undefined,
                true
              ),
            { discrete: true }
          )
        })
        const result = serializeEditorToMarkdown(
          testEnv.editor.getEditorState()
        )
        expect(result).toBe(text)
      })
    },
    editorConfig,
    <Plugins />
  )
})
